// 100+ tarot card interpretations in multiple languages
export const tarotVariations: Record<number, Record<string, string[]>> = {
  1: {
    en: [
      "New beginning, fresh start, spontaneity and risk-taking",
      "Unlimited potential and infinite possibilities ahead",
      "Youthful energy and carefree spirit guiding your path",
      "Divine fool's journey begins with a single step",
      "Innocence before experience transforms your world",
      "Adventure calls - embrace the unknown with courage",
      "Trust the universe, leap into uncharted territory",
      "Foolish wisdom leads to greatest discoveries",
      "New chapter unfolds with pure intention and faith",
      "Destiny beckons - answer the call of adventure",
    ],
    ru: [
      "Новое начало, свежий старт и спонтанность",
      "Бесконечный потенциал и возможности впереди",
      "Молодая энергия и беззаботный дух",
      "Путешествие Дурака - первый шаг судьбы",
      "Невинность перед опытом трансформирует мир",
      "Приключение зовет - примите неизвестное",
      "Доверьте себя судьбе и вселенной",
      "Дурацкая мудрость ведет к великим открытиям",
      "Новая глава разворачивается с чистым намерением",
      "Судьба зовет - ответьте на зов приключения",
    ],
    ro: [
      "Nou început, start proaspăt și spontaneitate",
      "Potențial nelimitat și posibilități infinite",
      "Energie tânără și spirit fără griji",
      "Calătoria Nebunului - primul pas al sorții",
      "Inocență transformă lumea prin experiență",
      "Aventura te cheamă - acceptă necunoscutul",
      "Încredință-te universului și sorții tale",
      "Înțelepciunea nebunului conduce la descoperiri mari",
      "Nou capitol se desfășoară cu intenție pură",
      "Soarta te cheamă - răspunde apelului aventurii",
    ],
    ua: [
      "Новий початок, свіжий старт та спонтанність",
      "Безмежний потенціал та нескінченні можливості",
      "Молода енергія та безтурботний дух",
      "Подорож Дурня - перший крок долі",
      "Невинність трансформує світ через досвід",
      "Пригода кличе - прийми невідоме",
      "Довіртеся всесвіту та своїй долі",
      "Дурна мудрість ведає до великих відкриттів",
      "Новий розділ розгортається з чистим наміром",
      "Доля кличе - відповіди на заклик пригоди",
    ],
  },
  2: {
    en: [
      "Balance between opposing forces creates harmony",
      "Sacred knowledge and intuitive wisdom guide you",
      "Hidden truths emerge from the subconscious realm",
      "Mystery deepens understanding of inner self",
      "Gateway between two worlds opens within",
      "Listen to the whispers of your inner voice",
      "Secrets reveal themselves in quiet moments",
      "Duality resolves through deeper perception",
      "Divine feminine wisdom awakens within",
      "Priestess guards the mysteries of your soul",
    ],
    ru: [
      "Баланс между противоположными силами создает гармонию",
      "Священные знания и интуитивная мудрость вас ведут",
      "Скрытые истины выходят из подсознания",
      "Тайна углубляет понимание внутреннего я",
      "Врата между двумя мирами открываются внутри",
      "Слушайте шепот вашего внутреннего голоса",
      "Секреты раскрываются в тихие моменты",
      "Двойственность разрешается через восприятие",
      "Божественная женская мудрость пробуждается",
      "Жрица хранит тайны вашей души",
    ],
    ro: [
      "Echilibrul între forțe opuse creează armonie",
      "Cunoștințele sacre și înțelepciunea intuitivă te ghidează",
      "Adevărurile ascunse ies din subconștient",
      "Misterul adâncește înțelegerea de sine",
      "Porțile dintre două lumi se deschid în interior",
      "Ascultă șoapele vocii tale interioare",
      "Secretele se dezvăluie în momente liniștite",
      "Dualitatea se rezolvă prin percepție mai profundă",
      "Înțelepciunea divină feminină se-ndeaaptă",
      "Preotesa păzește misterele sufletului tău",
    ],
    ua: [
      "Баланс між протилежними силами створює гармонію",
      "Священні знання та інтуїтивна мудрість вас ведуть",
      "Приховані істини виходять з підсвідомості",
      "Таємниця поглиблює розуміння внутрішнього я",
      "Врата між двома світами відкриваються всередину",
      "Слухайте біллого вашого внутрішнього голосу",
      "Секрети розкриваються в тихі моменти",
      "Двоїстість розв'язується через глибше сприйняття",
      "Божественна жіноча мудрість пробуджується",
      "Жриця охороняє таємниці вашої душі",
    ],
  },
}

export function getRandomVariation(cardNumber: number, lang: string): string {
  const variations = tarotVariations[cardNumber]?.[lang] || tarotVariations[cardNumber]?.en || []
  if (variations.length === 0) return ""
  return variations[Math.floor(Math.random() * variations.length)]
}
